# Generated by Django 2.2.4 on 2022-09-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_msisdn', models.CharField(max_length=250)),
                ('offer_name', models.CharField(max_length=250)),
                ('text_message', models.CharField(max_length=250)),
                ('job_category', models.CharField(max_length=250)),
                ('job_location', models.CharField(max_length=250, null=True)),
                ('offer_code', models.CharField(max_length=250)),
                ('extra_satus', models.BooleanField(default=False)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_msisdn', models.CharField(max_length=250)),
                ('offer_name', models.CharField(max_length=250)),
                ('text_message', models.CharField(max_length=250)),
                ('job_category', models.CharField(max_length=250)),
                ('job_location', models.CharField(max_length=250, null=True)),
                ('offer_code', models.CharField(max_length=250)),
                ('extra_satus', models.BooleanField(default=False)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
            },
        ),
        migrations.CreateModel(
            name='IncomingSmsSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('dest_msisdn', models.CharField(max_length=16)),
                ('text_message', models.CharField(max_length=300)),
                ('sender_name', models.CharField(max_length=300)),
                ('link_id', models.CharField(max_length=300)),
                ('correlator', models.CharField(max_length=300)),
                ('send_time', models.CharField(max_length=300)),
                ('service_id', models.CharField(max_length=300)),
                ('product_id', models.CharField(max_length=300)),
                ('client', models.CharField(max_length=300)),
                ('service_type', models.IntegerField()),
                ('sent_flag', models.CharField(max_length=300)),
                ('export_response', models.CharField(max_length=300)),
                ('ring_filter', models.CharField(max_length=300)),
                ('responded', models.CharField(max_length=300)),
                ('sub_type', models.CharField(max_length=300)),
                ('in_date', models.DateTimeField(auto_now_add=True)),
                ('to_sub', models.IntegerField()),
                ('processed', models.IntegerField()),
                ('sub_status', models.CharField(max_length=200)),
                ('offer_name', models.CharField(max_length=200)),
                ('offer_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(null=True)),
                ('dest_msisdn', models.CharField(max_length=16)),
                ('text_message', models.CharField(max_length=300)),
                ('delivery_status', models.CharField(max_length=300, null=True)),
                ('link_id', models.CharField(max_length=300, null=True)),
                ('correlator', models.CharField(default=0, max_length=300)),
                ('send_time', models.CharField(max_length=300, null=True)),
                ('offer_code', models.CharField(max_length=100)),
                ('offer_name', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=300, null=True)),
                ('client', models.CharField(max_length=300, null=True)),
                ('misc', models.CharField(max_length=300, null=True)),
                ('schedule_date', models.DateTimeField(auto_now_add=True)),
                ('oc', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=11, null=True)),
                ('request_identifier', models.CharField(max_length=200, null=True)),
                ('smstrackcode', models.IntegerField()),
                ('send_date', models.DateField(null=True)),
                ('sent', models.CharField(max_length=10, null=True)),
                ('extra_status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingSmsDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(null=True)),
                ('dest_msisdn', models.CharField(max_length=16)),
                ('text_message', models.CharField(max_length=300)),
                ('delivery_status', models.CharField(max_length=300, null=True)),
                ('link_id', models.CharField(max_length=300, null=True)),
                ('correlator', models.CharField(default=0, max_length=300)),
                ('send_time', models.CharField(max_length=300, null=True)),
                ('offer_code', models.CharField(max_length=100)),
                ('offer_name', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=300, null=True)),
                ('client', models.CharField(max_length=300, null=True)),
                ('misc', models.CharField(max_length=300, null=True)),
                ('schedule_date', models.DateTimeField(auto_now_add=True)),
                ('oc', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=11, null=True)),
                ('request_identifier', models.CharField(max_length=200, null=True)),
                ('smstrackcode', models.IntegerField()),
                ('send_date', models.DateField(null=True)),
                ('sent', models.CharField(max_length=10, null=True)),
                ('extra_status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShortCodeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
