# Generated by Django 2.2.4 on 2022-09-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='ROBERMS_LTD', max_length=50)),
                ('text_message', models.TextField(max_length=600, null=True)),
                ('track_code', models.CharField(max_length=50, null=True)),
                ('scheduled_time', models.DateTimeField()),
                ('sender_type', models.IntegerField(choices=[(1, 'Promotional'), (2, 'Transactional')], default=1)),
                ('active', models.BooleanField(default=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=200)),
                ('usage_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ScheduledMessage',
                'verbose_name_plural': 'ScheduledMessage',
            },
        ),
        migrations.CreateModel(
            name='SchedulePerMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='ROBERMS_LTD', max_length=50)),
                ('text_message', models.TextField(max_length=3000)),
                ('phone_number', models.CharField(max_length=500)),
                ('send_on', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
